name: tinkoff_id_web
description: Tinkoff Id WebToApp Flutter Realization
version: 1.0.1
homepage: https://kodefabrique.com

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.0.2
  pkce: ^1.1.0+1
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:


